name: github-samples

ghc-options: -Wall

dependencies:
  - base
  - base-compat
  - github
  - text

library:
  source-dirs: src

executables:
  github-show-user:
    main: ShowUser.hs
    source-dirs: Users
    dependencies:
      - github-samples
  github-show-user-2:
    main: ShowUser2.hs
    source-dirs: Users
    dependencies:
      - github-samples
  github-list-followers-example:
    main: Example.hs
    source-dirs: Users/Followers
  github-list-followers:
    main: ListFollowers.hs
    source-dirs: Users/Followers
    dependencies:
      - github-samples
  github-list-following:
    main: ListFollowing.hs
    source-dirs: Users/Followers
    dependencies:
      - github-samples
  github-delete-team:
    main: DeleteTeam.hs
    source-dirs: Teams
    dependencies:
      - github-samples
  github-edit-team:
    main: EditTeam.hs
    source-dirs: Teams
    dependencies:
      - github-samples
  github-list-team-current:
    main: ListTeamsCurrent.hs
    source-dirs: Teams
    dependencies:
      - github-samples
  github-list-team-repos:
    main: ListRepos.hs
    source-dirs: Teams
    dependencies:
      - github-samples
  github-teaminfo-for:
    main: TeamInfoFor.hs
    source-dirs: Teams
    dependencies:
      - github-samples
  github-add-team-membership-for:
    main: AddTeamMembershipFor.hs
    source-dirs: Teams/Memberships
    dependencies:
      - github-samples
  github-delete-team-membership-for:
    main: DeleteTeamMembershipFor.hs
    source-dirs: Teams/Memberships
    dependencies:
      - github-samples
  github-team-membership-info-for:
    main: TeamMembershipInfoFor.hs
    source-dirs: Teams/Memberships
    dependencies:
      - github-samples
  github-operational:
    main: Operational.hs
    source-dirs: Operational
    dependencies:
      - github-samples
      - http-client
      - http-client-tls
      - operational
      - transformers
      - transformers-compat
  github-list-deploy-keys-for:
    main: ListDeployKeys.hs
    source-dirs: Repos/DeployKeys
    dependencies:
      - github-samples
      - vector
  github-show-deploy-key:
    main: ShowDeployKey.hs
    source-dirs: Repos/DeployKeys
    dependencies:
      - github-samples
  github-create-deploy-key:
    main: CreateDeployKey.hs
    source-dirs: Repos/DeployKeys
    dependencies:
      - github-samples
  github-delete-deploy-key:
    main: DeleteDeployKey.hs
    source-dirs: Repos/DeployKeys
    dependencies:
      - github-samples
  github-searchrepos:
    main: SearchRepos.hs
    source-dirs: Search
    dependencies:
      - time
